package model;



/**
 * TabGysinfo generated by MyEclipse - Hibernate Tools
 */

public class GongYingShangGL  implements java.io.Serializable {


    // Fields    

     private String id;
     private String name;
     private String Gysdw;
     private String address;
     private String youxiang;
     private String lname1;
     private String lname2;
     private String ltel1;
     private String ltel2;
     private String yh;
     private String hao;


    // Constructors

    /** default constructor */
    public GongYingShangGL() {
    }

	/** minimal constructor */
    public GongYingShangGL(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public GongYingShangGL(String id, String name, String Gysdw, String address, String youxiang, String lname1, String lname2, String ltel1, String ltel2, String yh, String khbeizhu) {
        this.id = id;
        this.name = name;
        this.Gysdw = Gysdw;
        this.address = address;
        this.youxiang = youxiang;
        this.lname1 = lname1;
        this.lname2 = lname2;
        this.ltel1 = ltel1;
        this.ltel2 = ltel2;
        this.yh = yh;
        this.hao = hao;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getGysdw() {
        return this.Gysdw;
    }
    
    public void setGysdw(String Gysdw) {
        this.Gysdw = Gysdw;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getyouxiang() {
        return this.youxiang;
    }
    
    public void setyouxiang(String youxiang) {
        this.youxiang = youxiang;
    }

    public String getLname1() {
        return this.lname1;
    }
    
    public void setLname1(String lname1) {
        this.lname1 = lname1;
    }

    public String getlname2() {
        return this.lname2;
    }
    
    public void setlname2(String lname2) {
        this.lname2 = lname2;
    }

    public String getLtel1() {
        return this.ltel1;
    }
    
    public void setLtel1(String ltel1) {
        this.ltel1 = ltel1;
    }

    public String getLtel2() {
        return this.ltel2;
    }
    
    public void setLtel2(String ltel2) {
        this.ltel2 = ltel2;
    }

    public String getYh() {
        return this.yh;
    }
    
    public void setYh(String yh) {
        this.yh = yh;
    }

    public String gethao() {
        return this.hao;
    }
    
    public void sethao(String hao) {
        this.hao = hao;
    }
   








}