package model;



/**
 * TabKhinfo generated by MyEclipse - Hibernate Tools
 */

public class KehuXX  implements java.io.Serializable {


    // Fields    

     private String id;
     private String khname;
     private String khdw;
     private String address;
     private String youxiang;
     private String lname1;
     private String lname2;
     private String ltel1;
     private String ltel2;
     private String khbeizhu;
     private String yinhang;
     private String hao;


    // Constructors

    /** default constructor */
    public KehuXX() {
    }

	/** minimal constructor */
    public KehuXX(String id) {
        this.id = id;
    }
    
    /** full constructor */
    public KehuXX(String id, String khname, String khdw, String address, String youxiang, String lname1, String lname2, String ltel1, String ltel2, String khbeizhu, String yinhang, String hao) {
        this.id = id;
        this.khname = khname;
        this.khdw = khdw;
        this.address = address;
        this.youxiang = youxiang;
        this.lname1 = lname1;
        this.lname2 = lname2;
        this.ltel1 = ltel1;
        this.ltel2 = ltel2;
        this.khbeizhu = khbeizhu;
        this.yinhang = yinhang;
        this.hao = hao;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getKhname() {
        return this.khname;
    }
    
    public void setKhname(String khname) {
        this.khname = khname;
    }

    public String getKhdw() {
        return this.khdw;
    }
    
    public void setKhdw(String khdw) {
        this.khdw = khdw;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getyouxiang() {
        return this.youxiang;
    }
    
    public void setyouxiang(String youxiang) {
        this.youxiang = youxiang;
    }

    public String getLname1() {
        return this.lname1;
    }
    
    public void setLname1(String lname1) {
        this.lname1 = lname1;
    }

    public String getlname2() {
        return this.lname2;
    }
    
    public void setlname2(String lname2) {
        this.lname2 = lname2;
    }

    public String getLtel1() {
        return this.ltel1;
    }
    
    public void setLian(String ltel1) {
        this.ltel1 = ltel1;
    }

    public String getLtel2() {
        return this.ltel2;
    }
    
    public void setLtel2(String ltel2) {
        this.ltel2 = ltel2;
    }

    public String getMail() {
        return this.khbeizhu;
    }
    
    public void setMail(String khbeizhu) {
        this.khbeizhu = khbeizhu;
    }

    public String getyinhang() {
        return this.yinhang;
    }
    
    public void setyinhang(String yinhang) {
        this.yinhang = yinhang;
    }

    public String getHao() {
        return this.hao;
    }
    
    public void setHao(String hao) {
        this.hao = hao;
    }
   








}